Algoritmo "SOMA TODOS 1_100"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   :  Leandro Gonzalez
// Descrição   : Imprima a soma de todos os números de 1 a 100
// Autor(a)    : George Pinchemel
// Data atual  : 19/04/2025
Var

   soma, n: inteiro

Inicio

   soma <- 0
   para i de 1 ate 100 faca
      soma <- soma + n
   fimpara
   escreva("A soma de todos os números de 1 até 100 é: ", soma)

Fimalgoritmo