Algoritmo "Area do quadrado"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Leandro Gonzalez
// Descrição   : Calcular a area do quadrado
// Autor(a)    : George Pinchemel
// Data atual  : 25/02/2025
Var

L, A: inteiro

Inicio

escreva ("Insira o valor do lado do quadrado: ")
leia (L)

A <- L*L

escreva ("O quadrado com o lado", L ," possui uma area de", A)

Fimalgoritmo