Algoritmo "Algarismo da Dezena"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   :  Leandro Gonzalez 
// Descrição   : Algarismo da Dezena
// Autor(a)    : George Pinchemel
// Data atual  : 06/03/2025
Var

   N1,D: inteiro

Inicio

   escreva ("Informe um numero inteiro de 3 digitos: ")
   leia (N1)
   
   D <- (N1 % 100) DIV 10
   
   escreva ("O algarismo da dezena do numero e", D)

Fimalgoritmo