Algoritmo "Area do triangulo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   :  Leandro Gonzalez 
// Descrição   : Calcura a area do triangulo
// Autor(a)    : George Pinchemel
// Data atual  : 25/02/2025
Var

B, H, A: real

Inicio

escreva ("Quanto e a base do triangulo: ")
leia (B)
escreva ("Quando e a altura do triangulo: ")
leia (H)

A <- B * H / 2

escreva ("A area do triangulo de base", B ,", altura", H ,", e", A)

Fimalgoritmo